import GoldbachCircleMethodCollisionOneDimensionalDenominatorEnergyV18559

/-!
# Goldbach V1.8.560: transfer to the finite totient fourth moment

The remaining one-dimensional product denominators form an injective image
inside `[1,Q]`.  Their fourth-power totient-ratio mass is therefore bounded
by the explicit full-prefix moment

`sum_{1 <= d <= Q} (d / phi(d))^4`.

This is a carrier-exact finite reduction.  No linear or asymptotic bound for
that moment is asserted here.
-/

set_option autoImplicit false

open scoped BigOperators Classical ComplexConjugate

namespace GoldbachCircleMethodCollisionTotientFourthMomentTransferV18560

open GoldbachCircleMethodBoundedConductorReindexV18117
open GoldbachCircleMethodCollisionOneDimensionalDenominatorEnergyV18559
open GoldbachCircleMethodCollisionTotientRatioEnvelopeV18556
open GoldbachCircleMethodLogCutoffPresieveBindingV18120
open GoldbachCircleMethodPairwiseActiveCostAggregationV18318
open GoldbachCircleMethodPrimitiveBaseSlotEnergyV18474

/-- Product denominators generated by the genuine admitted complement
carrier of one conductor. -/
def activeProductDenominatorCarrier {Q : ℕ}
    (s : PositiveLevel Q) : Finset ℕ :=
  (activeComplementCarrier s).image (fun k => s.val * k.val)

/-- Distinct complements give distinct product denominators because the
fixed conductor is positive. -/
theorem active_product_denominator_injective {Q : ℕ}
    (s : PositiveLevel Q) :
    Set.InjOn (fun k : PositiveLevel Q => s.val * k.val)
      (activeComplementCarrier s) := by
  intro k _hk l _hl hkl
  apply Subtype.ext
  exact Nat.mul_left_cancel (NeZero.pos s.val) hkl

/-- Every admitted product denominator lies in the exact positive prefix
`[1,Q]`. -/
theorem activeProductDenominatorCarrier_subset_Icc {Q : ℕ}
    (s : PositiveLevel Q) :
    activeProductDenominatorCarrier s ⊆ Finset.Icc 1 Q := by
  intro d hd
  rw [activeProductDenominatorCarrier, Finset.mem_image] at hd
  rcases hd with ⟨k, hk, rfl⟩
  have hactive := (Finset.mem_filter.mp hk).2
  exact Finset.mem_Icc.mpr ⟨
    Nat.one_le_iff_ne_zero.mpr
      (mul_ne_zero (NeZero.ne s.val) (NeZero.ne k.val)),
    hactive.1⟩

/-- The full finite fourth moment that remains after collision reindexing. -/
noncomputable def totientRatioFourthMoment (Q : ℕ) : ℝ :=
  ∑ d ∈ Finset.Icc 1 Q, levelTotientRatio d ^ 4

/-- Exact injective reindexing of the admitted complement sum by its product
denominator. -/
theorem active_complement_totient_fourth_sum_eq_denominatorCarrier
    {Q : ℕ} (s : PositiveLevel Q) :
    (∑ k ∈ activeComplementCarrier s,
      levelTotientRatio (s.val * k.val) ^ 4) =
      ∑ d ∈ activeProductDenominatorCarrier s,
        levelTotientRatio d ^ 4 := by
  unfold activeProductDenominatorCarrier
  rw [Finset.sum_image (active_product_denominator_injective s)]

/-- Positivity embeds the genuine product-denominator mass into the full
prefix fourth moment without a cardinality loss. -/
theorem active_complement_totient_fourth_sum_le_moment
    {Q : ℕ} (s : PositiveLevel Q) :
    (∑ k ∈ activeComplementCarrier s,
      levelTotientRatio (s.val * k.val) ^ 4) ≤
      totientRatioFourthMoment Q := by
  rw [active_complement_totient_fourth_sum_eq_denominatorCarrier]
  unfold totientRatioFourthMoment
  exact Finset.sum_le_sum_of_subset_of_nonneg
    (activeProductDenominatorCarrier_subset_Icc s)
    (fun d _hd _hnot => by positivity)

/-- Envelope obtained by replacing the admitted denominator mass with its
full-prefix fourth moment. -/
noncomputable def collisionTotientFourthMomentEnvelopeEnergy
    (Q B : ℕ) (H V : ℝ) (r s : PositiveLevel Q) : ℝ :=
  ∑ N ∈ blockCarrier B,
    ∑ ψ : {ψ : DirichletCharacter ℂ s.val // ψ.IsPrimitive},
      ∑ χ : {χ : DirichletCharacter ℂ r.val // χ.IsPrimitive},
        totientRatioFourthMoment Q * V ^ 4 *
          ‖primitiveBaseSlotSource Q B N H ⟨r, χ⟩‖ ^ 2 *
          ‖primitiveBaseSlotSource Q B N H ⟨s, ψ⟩‖ ^ 2

/-- The one-dimensional collision envelope is controlled by the single
finite arithmetic moment, with the source energies unchanged. -/
theorem collisionOneDimensionalDenominatorRatioEnvelopeEnergy_le_moment
    (Q B : ℕ) (H V : ℝ) (r s : PositiveLevel Q) :
    collisionOneDimensionalDenominatorRatioEnvelopeEnergy Q B H V r s ≤
      collisionTotientFourthMomentEnvelopeEnergy Q B H V r s := by
  unfold collisionOneDimensionalDenominatorRatioEnvelopeEnergy
    collisionTotientFourthMomentEnvelopeEnergy
  apply Finset.sum_le_sum
  intro N _hN
  apply Finset.sum_le_sum
  intro ψ _hψ
  apply Finset.sum_le_sum
  intro χ _hχ
  let C := V ^ 4 *
    ‖primitiveBaseSlotSource Q B N H ⟨r, χ⟩‖ ^ 2 *
    ‖primitiveBaseSlotSource Q B N H ⟨s, ψ⟩‖ ^ 2
  have hC : 0 ≤ C := by
    dsimp only [C]
    positivity
  calc
    (∑ k ∈ activeComplementCarrier s,
      levelTotientRatio (s.val * k.val) ^ 4 * V ^ 4 *
        ‖primitiveBaseSlotSource Q B N H ⟨r, χ⟩‖ ^ 2 *
        ‖primitiveBaseSlotSource Q B N H ⟨s, ψ⟩‖ ^ 2) =
      (∑ k ∈ activeComplementCarrier s,
        levelTotientRatio (s.val * k.val) ^ 4) * C := by
        dsimp only [C]
        rw [Finset.sum_mul]
        apply Finset.sum_congr rfl
        intro k _hk
        ring
    _ ≤ totientRatioFourthMoment Q * C :=
      mul_le_mul_of_nonneg_right
        (active_complement_totient_fourth_sum_le_moment s) hC
    _ = totientRatioFourthMoment Q * V ^ 4 *
        ‖primitiveBaseSlotSource Q B N H ⟨r, χ⟩‖ ^ 2 *
        ‖primitiveBaseSlotSource Q B N H ⟨s, ψ⟩‖ ^ 2 := by
      dsimp only [C]
      ring

end GoldbachCircleMethodCollisionTotientFourthMomentTransferV18560
